"""fourth

Revision ID: 0f8bffbbb103
Revises: fe339d1ccbc8
Create Date: 2024-08-26 16:34:40.356132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8bffbbb103'
down_revision = 'fe339d1ccbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_allowance_prices_japan')
    with op.batch_alter_table('allowance_prices_japan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=False))
        batch_op.drop_index('ix_allowance_prices_japan_order')
        batch_op.drop_column('order')

    with op.batch_alter_table('allowance_prices_world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=False))
        batch_op.drop_index('ix_allowance_prices_world_order')
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_prices_world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), nullable=False))
        batch_op.create_index('ix_allowance_prices_world_order', ['order'], unique=False)
        batch_op.drop_column('note')

    with op.batch_alter_table('allowance_prices_japan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), nullable=False))
        batch_op.create_index('ix_allowance_prices_japan_order', ['order'], unique=False)
        batch_op.drop_column('note')

    op.create_table('_alembic_tmp_allowance_prices_japan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('allowance', sa.INTEGER(), nullable=False),
    sa.Column('is_show', sa.BOOLEAN(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
