"""fourth

Revision ID: 21c579c5e056
Revises: f0148c7d9196
Create Date: 2024-08-07 11:06:42.403248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c579c5e056'
down_revision = 'f0148c7d9196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions2', schema=None) as batch_op:
        batch_op.alter_column('allowance',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions2', schema=None) as batch_op:
        batch_op.alter_column('allowance',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
