"""fifth

Revision ID: 38ed5215689c
Revises: 0f8bffbbb103
Create Date: 2024-08-27 17:41:23.139113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ed5215689c'
down_revision = '0f8bffbbb103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_prices_japan', schema=None) as batch_op:
        batch_op.drop_index('ix_allowance_prices_japan_is_show')
        batch_op.drop_column('is_show')

    with op.batch_alter_table('allowance_prices_world', schema=None) as batch_op:
        batch_op.drop_index('ix_allowance_prices_world_is_show')
        batch_op.drop_column('is_show')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_prices_world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show', sa.BOOLEAN(), nullable=False))
        batch_op.create_index('ix_allowance_prices_world_is_show', ['is_show'], unique=False)

    with op.batch_alter_table('allowance_prices_japan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show', sa.BOOLEAN(), nullable=False))
        batch_op.create_index('ix_allowance_prices_japan_is_show', ['is_show'], unique=False)

    # ### end Alembic commands ###
