"""second

Revision ID: 741d0b23e64c
Revises: 1c8233952377
Create Date: 2024-08-20 14:30:36.840482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741d0b23e64c'
down_revision = '1c8233952377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowances', schema=None) as batch_op:
        batch_op.alter_column('calendars',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowances', schema=None) as batch_op:
        batch_op.alter_column('calendars',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
