"""empty message

Revision ID: 8875bbefab36
Revises: 21c579c5e056
Create Date: 2024-08-19 17:04:21.407347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8875bbefab36'
down_revision = '21c579c5e056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('applying_date', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('unit_prices', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('days', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_moves', schema=None) as batch_op:
        batch_op.drop_column('days')
        batch_op.drop_column('unit_prices')
        batch_op.drop_column('applying_date')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
