"""first

Revision ID: a0828fca06f5
Revises: 
Create Date: 2024-08-07 09:16:27.471435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0828fca06f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountItemName', sa.String(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_items_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_items_order'), ['order'], unique=False)

    op.create_table('allowance_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('decimal', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_show_japan', sa.Boolean(), nullable=False),
    sa.Column('is_show_world', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_order'), ['order'], unique=False)

    op.create_table('locations1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations1', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations1_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations1_order'), ['order'], unique=False)

    op.create_table('locations2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations2_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations2_order'), ['order'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paymentMethodName', sa.String(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_methods_order'), ['order'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiptName', sa.String(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_order'), ['order'], unique=False)

    op.create_table('regions2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions2_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_regions2_order'), ['order'], unique=False)

    op.create_table('supported_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supportedTypeName', sa.String(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supported_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supported_types_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_supported_types_order'), ['order'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('start', sa.String(length=255), nullable=False),
    sa.Column('end', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travelName', sa.String(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('travel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_travel_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_travel_order'), ['order'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.String(length=255), nullable=False),
    sa.Column('detail_number', sa.String(length=255), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('service_number', sa.String(length=255), nullable=False),
    sa.Column('service_card_number', sa.String(length=255), nullable=False),
    sa.Column('quote_number', sa.String(length=255), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=255), nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=False),
    sa.Column('support_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['support_type_id'], ['supported_types.id'], ),
    sa.ForeignKeyConstraint(['travel_id'], ['travel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.String(length=255), nullable=False),
    sa.Column('return_date', sa.String(length=255), nullable=False),
    sa.Column('allowance_move_id', sa.Integer(), nullable=False),
    sa.Column('calendars', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['allowance_move_id'], ['allowance_moves.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('account_item_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('applying_date', sa.String(length=255), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_item_id'], ['account_items.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('foreign_currency', sa.Float(), nullable=False),
    sa.Column('temporary_payment', sa.Float(), nullable=False),
    sa.Column('remaining_payment', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    op.drop_table('details')
    op.drop_table('allowances')
    op.drop_table('order')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('travel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_travel_order'))
        batch_op.drop_index(batch_op.f('ix_travel_is_show'))

    op.drop_table('travel')
    op.drop_table('task')
    with op.batch_alter_table('supported_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supported_types_order'))
        batch_op.drop_index(batch_op.f('ix_supported_types_is_show'))

    op.drop_table('supported_types')
    with op.batch_alter_table('regions2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions2_order'))
        batch_op.drop_index(batch_op.f('ix_regions2_is_show'))

    op.drop_table('regions2')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_order'))
        batch_op.drop_index(batch_op.f('ix_receipts_is_show'))

    op.drop_table('receipts')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_order'))
        batch_op.drop_index(batch_op.f('ix_payment_methods_is_show'))

    op.drop_table('payment_methods')
    with op.batch_alter_table('locations2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations2_order'))
        batch_op.drop_index(batch_op.f('ix_locations2_is_show'))

    op.drop_table('locations2')
    with op.batch_alter_table('locations1', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations1_order'))
        batch_op.drop_index(batch_op.f('ix_locations1_is_show'))

    op.drop_table('locations1')
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_order'))

    op.drop_table('currencies')
    op.drop_table('allowance_moves')
    with op.batch_alter_table('account_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_items_order'))
        batch_op.drop_index(batch_op.f('ix_account_items_is_show'))

    op.drop_table('account_items')
    # ### end Alembic commands ###
