"""second

Revision ID: cd9c978e6319
Revises: a0828fca06f5
Create Date: 2024-08-07 09:20:57.655671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9c978e6319'
down_revision = 'a0828fca06f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
