"""third

Revision ID: fe339d1ccbc8
Revises: 741d0b23e64c
Create Date: 2024-08-26 13:12:49.214221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe339d1ccbc8'
down_revision = '741d0b23e64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowance_prices_japan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowance_prices_japan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowance_prices_japan_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_allowance_prices_japan_order'), ['order'], unique=False)

    op.create_table('allowance_prices_world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowance_prices_world', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowance_prices_world_is_show'), ['is_show'], unique=False)
        batch_op.create_index(batch_op.f('ix_allowance_prices_world_order'), ['order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance_prices_world', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowance_prices_world_order'))
        batch_op.drop_index(batch_op.f('ix_allowance_prices_world_is_show'))

    op.drop_table('allowance_prices_world')
    with op.batch_alter_table('allowance_prices_japan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowance_prices_japan_order'))
        batch_op.drop_index(batch_op.f('ix_allowance_prices_japan_is_show'))

    op.drop_table('allowance_prices_japan')
    # ### end Alembic commands ###
